version: '3'

services:
        db:
                image: mysql:5.6
                restart: on-failure
                ports:
                        - "3308:3306"
                environment:
                          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                          MYSQL_USER: ${MYSQL_USER}
                          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                          MYSQL_DATABASE: ${MYSQL_DATABASE}
        nginx:
                image: nginx:alpine
                restart: on-failure
                ports:
                - ${NGINX_PORT}:80
                volumes:
                        - "./docker/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
                        - "./crowdin:/var/www/local.dev"
                depends_on:
                        - php

        php:
                build: 
                        context: .
                        dockerfile: docker/php/Dockerfile
                restart: on-failure
                volumes:
                        - "./crowdin:/var/www/local.dev"
                user: ${LOCAL_USER}
                expose:
                        - 900
                links:
                        - "db:db"
                        - "maildev:maildev"
        encore:
                image: library/node:10-alpine
                volumes:
                - "./crowdin:/var/www/local.dev"
                ports:
                - "${DEV_SERVER_PORT}:8080"
                working_dir: "/var/www/local.dev"
                command:  ["yarn", "dev-server", "--host=0.0.0.0"]
        maildev:
                image: maildev/maildev
                ports:
                - "1080:81"

        #phpmyadmin
        adminer:
                image: adminer
                restart: on-failure
                ports:
                - ${ADMINER_PORT}:8080




